<?php
/** Marketing & Growth, AI & Automation — see partials/blog-data.php for the format. */
return [
    'leads' => [
        'name'  => 'Leads',
        'cat'   => 'growth',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Capture enquiries from every channel and follow them up until they convert.',
        'title' => 'Leads: turn every enquiry into a patient',
        'desc'  => 'Capture enquiries from your website, calls, WhatsApp and campaigns in HealthO Pro Leads, assign follow-ups and track conversion to patients.',
        'intro' => 'Every call, website form and WhatsApp message is a potential patient, and many are lost simply because nobody followed up. HealthO Pro Leads captures enquiries from every channel and keeps them moving until they book.',
        'points' => [
            ['Capture from every channel', 'Website forms, calls, WhatsApp, walk-ins and campaigns.'],
            ['Assign and follow up', 'Assign leads to staff with follow-up dates.'],
            ['Lead status', 'Track each lead from new to contacted to converted.'],
            ['Source tracking', 'Know which channels and campaigns bring patients.'],
            ['Convert to booking', 'Turn a lead into an appointment or registration directly.'],
        ],
        'benefits' => [
            'Fewer lost enquiries.',
            'Accountability for follow-ups.',
            'Marketing spend focused on what works.',
            'Higher conversion rates.',
        ],
        'faqs' => [
            'Where do leads come from in HealthO Pro?' => 'Website forms, calls, WhatsApp, walk-ins and campaigns can all be captured as leads.',
            'Can we see which channel converts best?' => 'Yes. Each lead records its source, so conversion can be compared by channel and campaign.',
        ],
    ],

    'web-integration' => [
        'name'  => 'Web Integration',
        'cat'   => 'growth',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Connect your website for online bookings, report downloads and enquiries.',
        'title' => 'Web Integration: make your website work for your facility',
        'desc'  => 'HealthO Pro Web Integration connects your website to your system — online bookings, report downloads, packages and enquiry forms, live.',
        'intro' => 'A website that only shows a phone number is a missed opportunity. HealthO Pro Web Integration connects your site to your live system, so visitors can book, pay, download reports and send enquiries directly.',
        'points' => [
            ['Online booking', 'Visitors book appointments or home collections from your site.'],
            ['Report download', 'Patients download their reports securely.'],
            ['Packages and prices', 'Show your packages and tests from the live master.'],
            ['Enquiry forms', 'Website enquiries arrive as leads.'],
            ['Online payment', 'Accept payments through the integrated gateway.'],
        ],
        'benefits' => [
            'More bookings outside working hours.',
            'Fewer calls to the front desk.',
            'Website content that is always current.',
            'Better local search visibility.',
        ],
        'faqs' => [
            'Can patients book from our own website?' => 'Yes. Web Integration adds live booking, report download and enquiry features to your existing website.',
            'Do website enquiries reach our team?' => 'Yes. Enquiries arrive in HealthO Pro as leads for follow-up.',
        ],
    ],

    'banner-management' => [
        'name'  => 'Banner Management',
        'cat'   => 'growth',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Publish promotional banners on your app and website from one place.',
        'title' => 'Banner Management: promote offers wherever patients look',
        'desc'  => 'Publish and schedule promotional banners on your patient app and website with HealthO Pro Banner Management — no developer needed.',
        'intro' => 'Seasonal offers, new services and health camps deserve to be seen. HealthO Pro Banner Management lets your team publish and schedule banners on your digital channels without waiting for a developer.',
        'points' => [
            ['Upload and publish', 'Add a banner image, link and text.'],
            ['Schedule', 'Set start and end dates so offers go live and expire on time.'],
            ['Placement', 'Choose where each banner appears.'],
            ['Branch targeting', 'Show different banners for different branches.'],
            ['Active overview', 'See which banners are live at any moment.'],
        ],
        'benefits' => [
            'Faster promotions.',
            'No expired offers left online.',
            'Consistent branding.',
            'Marketing independence from IT.',
        ],
        'faqs' => [
            'Can banners be scheduled?' => 'Yes. Each banner has start and end dates and goes live and comes down automatically.',
            'Do we need a developer to change banners?' => 'No. Banners are managed from HealthO Pro by your own team.',
        ],
    ],

    'bulk-sms' => [
        'name'  => 'Bulk SMS',
        'cat'   => 'growth',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Send reminders, alerts and campaigns by SMS to selected patient groups.',
        'title' => 'Bulk SMS: reach every patient in one send',
        'desc'  => 'Send reminders, report alerts and health campaigns by SMS to filtered patient groups with HealthO Pro Bulk SMS, with delivery reports.',
        'intro' => 'SMS still reaches almost every phone. HealthO Pro Bulk SMS sends automatic alerts and targeted campaigns to the right patients without exporting lists or using separate tools.',
        'points' => [
            ['Automatic alerts', 'Booking confirmations, reminders and report-ready messages.'],
            ['Campaigns', 'Send health camp and offer messages to selected groups.'],
            ['Patient filters', 'Target by age, gender, last visit, test or branch.'],
            ['Templates', 'Reuse approved message templates.'],
            ['Delivery reports', 'See what was sent and delivered.'],
        ],
        'benefits' => [
            'Fewer no-shows.',
            'Low-cost patient re-engagement.',
            'No manual list handling.',
            'Measurable campaigns.',
        ],
        'faqs' => [
            'Can we send SMS to a specific group of patients?' => 'Yes. Patients can be filtered by details such as last visit, test, age, gender or branch before sending.',
            'Are SMS alerts sent automatically?' => 'Yes. Confirmations, reminders and report alerts can be sent automatically as events happen.',
        ],
    ],

    'official-whatsapp' => [
        'name'  => 'Official WhatsApp',
        'cat'   => 'growth',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Send reports, bills and reminders from your verified WhatsApp Business number.',
        'title' => 'Official WhatsApp: reports and reminders on the app patients use most',
        'desc'  => 'Send reports, bills, reminders and campaigns from your official WhatsApp Business number with HealthO Pro — automated and on-brand.',
        'intro' => 'For most patients, WhatsApp is where they actually read messages. HealthO Pro Official WhatsApp sends reports, bills and reminders from your business number automatically, so patients receive them where they look.',
        'points' => [
            ['Official business number', 'Messages come from your own WhatsApp Business identity.'],
            ['Report and bill delivery', 'Send PDFs as soon as reports are released.'],
            ['Reminders', 'Appointment, follow-up and payment reminders.'],
            ['Approved templates', 'Use message templates approved for business messaging.'],
            ['Campaigns', 'Share health packages and offers with opted-in patients.'],
        ],
        'benefits' => [
            'Higher read rates than SMS or email.',
            'Fewer “is my report ready?” calls.',
            'A trusted, branded channel.',
            'Less printing and courier cost.',
        ],
        'faqs' => [
            'Can reports be sent on WhatsApp automatically?' => 'Yes. When a report is released it can be sent to the patient on WhatsApp automatically.',
            'Do messages come from our own number?' => 'Yes. Messages are sent from your official WhatsApp Business number.',
        ],
    ],

    'bulk-emails' => [
        'name'  => 'Bulk Emails',
        'cat'   => 'growth',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Email reports, statements, newsletters and campaigns to patients and partners.',
        'title' => 'Bulk Emails: reports, statements and campaigns by email',
        'desc'  => 'Email reports, invoices, partner statements and newsletters in bulk with HealthO Pro Bulk Emails, using templates and patient filters.',
        'intro' => 'Email remains the preferred channel for corporates, partners and many patients. HealthO Pro Bulk Emails sends transactional emails automatically and campaigns to the audiences you choose.',
        'points' => [
            ['Report and invoice emails', 'Send documents automatically when they are ready.'],
            ['Partner statements', 'Email periodic statements to B2B partners and corporates.'],
            ['Newsletters and campaigns', 'Send updates and offers to selected groups.'],
            ['Templates', 'Branded email templates.'],
            ['Send history', 'See what was sent to whom.'],
        ],
        'benefits' => [
            'Professional communication with partners.',
            'Less manual emailing.',
            'Low-cost patient engagement.',
            'A record of every message.',
        ],
        'faqs' => [
            'Can reports be emailed automatically?' => 'Yes. Reports and invoices can be emailed automatically when they are ready.',
            'Can we email statements to partners?' => 'Yes. Periodic statements can be emailed to B2B partners and corporate clients.',
        ],
    ],

    'medical-representative-management' => [
        'name'  => 'Medical Representative Management',
        'cat'   => 'growth',
        'for'   => ['lims', 'hims', 'ris', 'cims'],
        'short' => 'Plan and track field staff visits to doctors, and the business they bring.',
        'title' => 'Medical Representative Management: measure every field visit',
        'desc'  => 'Plan and track medical representative visits to doctors and partners in HealthO Pro, and link them to the referrals and revenue they bring.',
        'intro' => 'Field teams build the doctor and partner relationships that bring referrals, but their work is hard to measure. HealthO Pro Medical Representative Management records visits and connects them to the business that follows.',
        'points' => [
            ['Visit planning', 'Plan daily visits to doctors, clinics and partners.'],
            ['Visit reporting', 'Representatives log visits and outcomes.'],
            ['Territory and doctor mapping', 'Assign doctors and areas to each representative.'],
            ['Business linkage', 'See referrals and revenue from each representative’s doctors.'],
            ['Performance reports', 'Compare representatives and territories.'],
        ],
        'benefits' => [
            'Visibility of field activity.',
            'Focus on high-value doctors.',
            'Fair, data-based incentives.',
            'Growth in referrals.',
        ],
        'faqs' => [
            'Can representatives log visits in HealthO Pro?' => 'Yes. Representatives record each visit and its outcome against the doctor or partner.',
            'Can we see the business each representative brings?' => 'Yes. Referrals and revenue from the doctors mapped to each representative are reported.',
        ],
    ],

    'forms-survey-testimonials' => [
        'name'  => 'Forms (Survey, Testimonials)',
        'cat'   => 'growth',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Build surveys and collect testimonials with shareable online forms.',
        'title' => 'Forms: surveys and testimonials without extra tools',
        'desc'  => 'Build patient and staff surveys and collect testimonials with HealthO Pro Forms — shareable links, responses in one place and simple reports.',
        'intro' => 'Satisfaction surveys, staff feedback and patient testimonials all need a form — often built in a separate tool and forgotten. HealthO Pro Forms keeps them inside the system you already use.',
        'points' => [
            ['Form builder', 'Create forms with ratings, choices and text questions.'],
            ['Share by link', 'Send forms by WhatsApp, SMS, email or QR code.'],
            ['Surveys', 'Measure patient or staff satisfaction over time.'],
            ['Testimonials', 'Collect written testimonials with permission to publish.'],
            ['Responses and reports', 'See all responses and summaries in one place.'],
        ],
        'benefits' => [
            'No separate form tools.',
            'Real voices for your marketing.',
            'Regular, measurable feedback.',
            'Responses linked to your data.',
        ],
        'faqs' => [
            'What kinds of forms can we create?' => 'Surveys, feedback forms and testimonial forms with ratings, multiple-choice and text questions.',
            'How are forms shared?' => 'By link through WhatsApp, SMS or email, or by QR code.',
        ],
    ],

    'healtho-ai-assistant' => [
        'name'  => 'HealthO AI Assistant',
        'cat'   => 'ai',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Ask questions about your data and get help with everyday tasks in plain language.',
        'title' => 'HealthO AI Assistant: ask your system, in plain language',
        'desc'  => 'The HealthO AI Assistant answers questions about your facility’s data and helps staff find information and complete tasks in plain language.',
        'intro' => 'Finding a number or a screen shouldn’t require training. The HealthO AI Assistant lets your team ask questions in everyday language and get answers and guidance from HealthO Pro.',
        'points' => [
            ['Plain-language questions', 'Ask things like “today’s collections by branch”.'],
            ['Quick answers', 'Get figures and summaries without building a report.'],
            ['Guidance', 'Get help on how to do a task in HealthO Pro.'],
            ['Role-aware', 'Answers respect each user’s access rights.'],
            ['Always available', 'Help at any hour, for every shift.'],
        ],
        'benefits' => [
            'Faster answers for managers.',
            'Quicker onboarding of new staff.',
            'Less dependence on a few experts.',
            'More use of the data you already have.',
        ],
        'faqs' => [
            'What can the HealthO AI Assistant do?' => 'Answer questions about your facility’s data in plain language and guide staff through tasks in HealthO Pro.',
            'Does the AI Assistant respect user permissions?' => 'Yes. Answers are limited to what each user is allowed to access.',
        ],
    ],

    'ai-call-agents' => [
        'name'  => 'AI Call Agents',
        'cat'   => 'ai',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'AI voice agents that answer and make calls for bookings, reminders and follow-ups.',
        'title' => 'AI Call Agents: never miss a patient call again',
        'desc'  => 'HealthO Pro AI Call Agents answer and place calls for bookings, reminders and follow-ups, around the clock, and log every call in your system.',
        'intro' => 'Busy front desks miss calls, and every missed call can be a missed patient. HealthO Pro AI Call Agents handle routine calls — bookings, reminders, report status, follow-ups — so your staff can focus on the patients in front of them.',
        'points' => [
            ['Inbound calls', 'Answer common questions and take bookings at any hour.'],
            ['Outbound reminders', 'Call patients about appointments, follow-ups and dues.'],
            ['Connected to your data', 'Agents use your live schedules and patient information.'],
            ['Hand-off to staff', 'Complex calls are passed to a person.'],
            ['Call logs', 'Every call and its outcome is recorded.'],
        ],
        'benefits' => [
            'No missed calls after hours.',
            'Less phone load on staff.',
            'More confirmed appointments.',
            'Consistent, courteous call handling.',
        ],
        'faqs' => [
            'What calls can AI Call Agents handle?' => 'Routine calls such as appointment booking, reminders, follow-ups and report-status enquiries, with complex calls handed to staff.',
            'Are AI calls recorded in HealthO Pro?' => 'Yes. Each call and its outcome is logged against the patient or lead.',
        ],
    ],

    'master-reminders' => [
        'name'  => 'Master Reminders',
        'cat'   => 'ai',
        'for'   => ['hims', 'lims', 'cims', 'ris'],
        'short' => 'Automated reminders for renewals, calibrations, dues and recurring tasks.',
        'title' => 'Master Reminders: never miss a renewal or deadline',
        'desc'  => 'Set automated reminders in HealthO Pro for licence renewals, equipment calibration, AMC dates, dues and recurring tasks — sent to the right person.',
        'intro' => 'Licences expire, equipment needs calibration and contracts need renewing — and these dates are easy to forget. HealthO Pro Master Reminders keeps every important date in one place and reminds the right person in time.',
        'points' => [
            ['Any recurring date', 'Licences, calibrations, AMCs, insurance and more.'],
            ['Advance reminders', 'Reminders a set number of days before the due date.'],
            ['Assigned owners', 'Each reminder goes to the person responsible.'],
            ['Repeat schedules', 'Monthly, quarterly and yearly repeats.'],
            ['Overdue view', 'See anything that was missed.'],
        ],
        'benefits' => [
            'No lapsed licences or contracts.',
            'Equipment stays compliant.',
            'Less reliance on memory and calendars.',
            'Clear responsibility.',
        ],
        'faqs' => [
            'What can Master Reminders be used for?' => 'Any recurring deadline, such as licence renewals, equipment calibration, AMC dates, insurance renewals and dues.',
            'Who receives the reminders?' => 'Each reminder is assigned to a responsible person, who is notified before the due date.',
        ],
    ],
];
